# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\"\x14\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t\",\n\tTextSplit\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tdelimiter\x18\x02 \x01(\t\"5\n\x11TextSplitResponse\x12\x11\n\tnum_parts\x18\x01 \x01(\x05\x12\r\n\x05parts\x18\x02 \x03(\t\"\x18\n\x06Number\x12\x0e\n\x06number\x18\x01 \x01(\x05\"2\n\x0fIsPrimeResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x0f\n\x07isprime\x18\x02 \x01(\x08\x32u\n\x07Service\x12\x17\n\x07reverse\x12\x05.Text\x1a\x05.Text\x12\'\n\x05split\x12\n.TextSplit\x1a\x12.TextSplitResponse\x12(\n\x07isprime\x12\x07.Number\x1a\x10.IsPrimeResponse(\x01\x30\x01\x62\x06proto3')
)




_TEXT = _descriptor.Descriptor(
  name='Text',
  full_name='Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='Text.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=37,
)


_TEXTSPLIT = _descriptor.Descriptor(
  name='TextSplit',
  full_name='TextSplit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='TextSplit.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delimiter', full_name='TextSplit.delimiter', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=83,
)


_TEXTSPLITRESPONSE = _descriptor.Descriptor(
  name='TextSplitResponse',
  full_name='TextSplitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_parts', full_name='TextSplitResponse.num_parts', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parts', full_name='TextSplitResponse.parts', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=138,
)


_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='Number.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=164,
)


_ISPRIMERESPONSE = _descriptor.Descriptor(
  name='IsPrimeResponse',
  full_name='IsPrimeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='IsPrimeResponse.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isprime', full_name='IsPrimeResponse.isprime', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=216,
)

DESCRIPTOR.message_types_by_name['Text'] = _TEXT
DESCRIPTOR.message_types_by_name['TextSplit'] = _TEXTSPLIT
DESCRIPTOR.message_types_by_name['TextSplitResponse'] = _TEXTSPLITRESPONSE
DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['IsPrimeResponse'] = _ISPRIMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), dict(
  DESCRIPTOR = _TEXT,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:Text)
  ))
_sym_db.RegisterMessage(Text)

TextSplit = _reflection.GeneratedProtocolMessageType('TextSplit', (_message.Message,), dict(
  DESCRIPTOR = _TEXTSPLIT,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:TextSplit)
  ))
_sym_db.RegisterMessage(TextSplit)

TextSplitResponse = _reflection.GeneratedProtocolMessageType('TextSplitResponse', (_message.Message,), dict(
  DESCRIPTOR = _TEXTSPLITRESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:TextSplitResponse)
  ))
_sym_db.RegisterMessage(TextSplitResponse)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), dict(
  DESCRIPTOR = _NUMBER,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  ))
_sym_db.RegisterMessage(Number)

IsPrimeResponse = _reflection.GeneratedProtocolMessageType('IsPrimeResponse', (_message.Message,), dict(
  DESCRIPTOR = _ISPRIMERESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:IsPrimeResponse)
  ))
_sym_db.RegisterMessage(IsPrimeResponse)



_SERVICE = _descriptor.ServiceDescriptor(
  name='Service',
  full_name='Service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=218,
  serialized_end=335,
  methods=[
  _descriptor.MethodDescriptor(
    name='reverse',
    full_name='Service.reverse',
    index=0,
    containing_service=None,
    input_type=_TEXT,
    output_type=_TEXT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='split',
    full_name='Service.split',
    index=1,
    containing_service=None,
    input_type=_TEXTSPLIT,
    output_type=_TEXTSPLITRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='isprime',
    full_name='Service.isprime',
    index=2,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_ISPRIMERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE)

DESCRIPTOR.services_by_name['Service'] = _SERVICE

# @@protoc_insertion_point(module_scope)
